# On every push this script is executed
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}